### ISSUE TITLE
archlinuxarm c201p [FAILED] Network Name Resolution

### ISSUE THREAD

**Issue by ProblemsArising** [nikolas-n/GNU-Linux-on-Asus-C201-Chromebook#10]
I followed your instructions and created the bootable usb then edited it. However, when I hit CTRL+U to boot it, I get stuck on Network Name Resolution. Load/Save RF Kill Switch Status fails once, but then starts so I've no issue with that. I've already went back through everything again and still no luck.
![20240528_232819](https://github.com/nikolas-n/GNU-Linux-on-Asus-C201-Chromebook/assets/171110323/a068fa6f-cd29-46be-b88f-0915c5cd85ac)

**Comment by ProblemsArising** [comment]
I was able to use a 2019 version on internet achive and it worked.

**Comment by ProblemsArising** [comment]
If you actually want to use and install anything current, you would have to update the system. This would cause this above error to occur, so I wouldn't recommend this for anyone who's not a developer or who knows a lot about systems (I don't... yet).

**Comment by kapouer** [comment]
debian bookworm can run c201 happily, however I've seen signs of demise recently, for example chromium 126 works but 128 segfaults.
