### ISSUE TITLE
Libreboot image

### ISSUE THREAD

**Issue by jgreen01** [nikolas-n/GNU-Linux-on-Asus-C201-Chromebook#6]
I can't find a Libreboot image for the C201. The Libreboot pages you've linked to don't have it either.

Do I have to compile my own image or does someone out there have a working image I can use? @nikolas-n?

**Comment by kapouer** [comment]
https://libreboot.org/download.html
https://www.mirrorservice.org/sites/libreboot.org/release/stable/20160907/rom/depthcharge/

**Comment by jgreen01** [comment]
Thank you @kapouer!
